// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgcZxNIi09pW-HoPjzC5StA_ep8-WtDQ',
    appId: '1:952791941209:web:5c52a387279347da613148',
    messagingSenderId: '952791941209',
    projectId: 'invmovieconcept1',
    authDomain: 'invmovieconcept1.firebaseapp.com',
    databaseURL: 'https://invmovieconcept1.firebaseio.com',
    storageBucket: 'invmovieconcept1.firebasestorage.app',
    measurementId: 'G-HQGTTHLNEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrtCEg_lerLm8Y80381ATXlZ5S3mQ2Qk',
    appId: '1:952791941209:android:f775bcd53b6db601613148',
    messagingSenderId: '952791941209',
    projectId: 'invmovieconcept1',
    databaseURL: 'https://invmovieconcept1.firebaseio.com',
    storageBucket: 'invmovieconcept1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd1W4BPSZ_nuSPyuJuJ8O9kJyoF6QfE7Q',
    appId: '1:952791941209:ios:98e58b72907ec4fe613148',
    messagingSenderId: '952791941209',
    projectId: 'invmovieconcept1',
    databaseURL: 'https://invmovieconcept1.firebaseio.com',
    storageBucket: 'invmovieconcept1.firebasestorage.app',
    androidClientId: '952791941209-fnvlolvt0ife0t9i6rv8q1gutufphal0.apps.googleusercontent.com',
    iosClientId: '952791941209-rt97fuoo8bnn5qnvm1uiiffdn9hpsl8d.apps.googleusercontent.com',
    iosBundleId: 'com.onemdev.invmovieconcept1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd1W4BPSZ_nuSPyuJuJ8O9kJyoF6QfE7Q',
    appId: '1:952791941209:ios:98e58b72907ec4fe613148',
    messagingSenderId: '952791941209',
    projectId: 'invmovieconcept1',
    databaseURL: 'https://invmovieconcept1.firebaseio.com',
    storageBucket: 'invmovieconcept1.firebasestorage.app',
    androidClientId: '952791941209-fnvlolvt0ife0t9i6rv8q1gutufphal0.apps.googleusercontent.com',
    iosClientId: '952791941209-rt97fuoo8bnn5qnvm1uiiffdn9hpsl8d.apps.googleusercontent.com',
    iosBundleId: 'com.onemdev.invmovieconcept1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPit16E4GJUDgrdhUUEa8W7im-FTgekc',
    appId: '1:952791941209:web:91999739b94ac425613148',
    messagingSenderId: '952791941209',
    projectId: 'invmovieconcept1',
    authDomain: 'invmovieconcept1.firebaseapp.com',
    databaseURL: 'https://invmovieconcept1.firebaseio.com',
    storageBucket: 'invmovieconcept1.firebasestorage.app',
    measurementId: 'G-YGTRKLLNJB',
  );
}
